# Values to configure postgres userdb

# Some global settings (obvi)
global:
  postgresql:
    servicePort: 5432
    postgresqlDatabase: studysnap_userdb # Note: This should match charts/authentication/values.yaml

# Authentication for database
postgresqlUsername: studysnap
existingSecret: ss-authentication

# Used to make it easier to get host on ClusterIP service
fullnameOverride: studysnap-userdb

service:
  type: ClusterIP
  port: 5432