apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
  name: {{ include "authentication.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.certManager.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentication.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentication.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}