apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ include "authentication.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentication.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}