apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "el-fulltextsearch.fullname" . }}-logstash-deployment
  namespace: {{ .Values.defaultNamespace }}
  labels:
    app: {{ include "el-fulltextsearch.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "el-fulltextsearch.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 45
  template:
    metadata:
      labels:
        app: {{ include "el-fulltextsearch.fullname" . }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Release.Name }}-logstash
          image: "{{ .Values.logstash.image.name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logstash.image.pullPolicy | default "Always" }}
          env:
            - name: DB_HOST
              value: "{{ include "postgresql.fullname" }}"
            - name: DB_PORT
              value: {{ .Values.database.port }}
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: ES_HOST
              value: "{{ include "elasticsearch.fullname" }}"
            - name: ES_PORT
              value: {{ .Values.elasticsearch.port }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: JWT_SECRET
          ports:
            - containerPort: {{ .Values.logstash.image.port }}
          volumes:
            - name: {{ include "el-fulltextsearch.fullname" . }}-cmv
              configMap:
                name: "logstash-configmap-{{ .Release.Name }}"
                items:
                  - key: logstash_conf
                    path: /usr/share/logstash/config/logstash.yml
                  - key: pipelines_conf
                    path: /usr/share/logstash/config/pipelines.yml
                  - key: note_pipeline
                    path: /usr/share/logstash/pipeline/notes.conf
          resources: {{- toYaml .Values.logstash.resources | nindent 12 }}