# Default values for the chart

# Application (global) values
restartPolicy: Always
secretName: studysnap-db-credentials

logstash:
  host: "0.0.0.0"
  secretPath: "/run/secrets/kubernetes.io/studysnap"
  secretGroup: "logstash/jdbcpassword"
  image:
    name: studysnap/logstash-pg-es
    tag: 1.x
    pullPolicy: Always
  resources: {}

database:
  hostname: studysnap-pg-db
  port: 5432
  name: studysnap_db

es:
  port: 9200

# OVERRIDE ELASTICSEARCH CHART VALUES (if needed)
elasticsearch:
  replicas: 1
  imageTag: 7.11.2
  esJavaOpts: "-Xms512m -Xmx512m"
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  extraVolumes:
    - name: elasticsearch-configv
      configMap:
        name: elasticsearch-config
  extraVolumeMounts:
    - name: elasticsearch-configv
      mountPath: /etc/elasticsearch/elasticsearch.yaml
      subPath: elasticsearch.yaml
  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi