# Default values for neptune chart

# Application Settings
secretName: ss-neptune
namespace: studysnap

# Application Image Settings
image:
  name: studysnap/neptune
  pullPolicy: Always
  restartPolicy: Always
  port: 7777
  env:
    maxRequests: 400
    dbUsername: studysnap
    dbDialect: postgres
    dbNoteDatabase: studysnap_notedb
    dbPort: 5432
    fileStore: /files/


# Expose service settings
service:
  type: ClusterIP
  port: 6000

# Let's Encrypt Settings (SSL)
ingress:
  host: studysnap.ca
  certManager:
    clusterIssuer: letsencrypt-prod
    tlsSecretName: ss-neptune-tls

# PVC
pvc:
  size: 8Gi
  storageClass: do-block-storage

# Override the resource configuration for read replicas
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# OVERRIDE POSTGRESQL VALUES (in dependency)
postgresql:
  fullnameOverride: studysnap-notedb
  startupProbe:
    enabled: false
  volumePermissions:
    enabled: true
  image:
    debug: true
  global:
    postgresql:
      servicePort: 5432
      postgresqlDatabase: studysnap_notedb # Note: This should match charts/neptune/values.yaml
  postgresqlUsername: studysnap
  existingSecret: ss-neptune
  service:
    type: ClusterIP
    port: 5432

# OVERRIDE AUTHENTICATIONs POSTGRESQL VALUES (authentication dep)
authentication:
  secretName: ss-authentication
  # TEMP (Disable startup probe)
  startupProbe:
    enabled: false
  volumePermissions:
    enabled: true
  image:
    debug: true
  postgresql:
    fullnameOverride: studysnap-userdb
    global:
      postgresql:
        servicePort: 5432
        postgresqlDatabase: studysnap_userdb # Note: This should match charts/authentication/values.yaml
    postgresqlUsername: studysnap
    existingSecret: ss-authentication
    service:
      type: ClusterIP
      port: 5432