# Default values for authentication chart

# Application Settings
restartPolicy: Always
secretName: ss-authentication
namespace: studysnap

# Application Image Settings
image:
  name: studysnap/authentication
  pullPolicy: Always
  port: 5555
  env:
    maxRequests: 250
    bcryptSaltRounds: 12
    dbDialect: postgres
    dbPort: 5432
    dbRetryAttempts: 5
    jwtAccessExpireTime: 5m


# Expose service settings
service:
  type: ClusterIP
  port: 5000

# Let's Encrypt Settings (SSL)
ingress:
  host: studysnap.ca
  certManager:
    clusterIssuer: letsencrypt-prod
    tlsSecretName: ss-authentication-tls

# Override the resource configuration for read replicas
resources: {}

# OVERRIDE POSTGRESQL VALUES (in dependency)
postgresql:
  fullnameOverride: studysnap-userdb
  startupProbe:
    enabled: false
  volumePermissions:
    enabled: true
  global:
    postgresql:
      servicePort: 5432
      postgresqlDatabase: studysnap_userdb # Note: This should match charts/authentication/values.yaml
  postgresqlUsername: studysnap
  existingSecret: ss-authentication
  service:
    type: ClusterIP
    port: 5432